# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: React CI/CD

# on:
#   push:
#     branches: [ master ]

# env:
#   # BASE_RELEASE_VERSION: "1.0"
#   CONTAINER_TAG: "platform/%Repo%" # TODO: replace '%Repo' with repo name
#   CONTAINER_REGISTRY: "nexus.employbridge.services:8082"

# jobs:
#   dev-deploy:

#     runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [12.x]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}

#     - run: npm install

#     - name: Modify configuration file - deployment yaml
#       uses: cschleiden/replace-tokens@v1
#       with:
#         files: '["./.env.production"]'

#     - run: npm run build --if-present
#     - run: npm test

#     - name: Import Secrets from Vault
#       uses: RichiCoder1/vault-action@v0.9.0
#       with:
#         url: https://vault.theatlastango.tools
#         method: approle
#         roleId: ${{ secrets.ATLAS_VAULT_ROLE_ID }}
#         secretId: ${{ secrets.ATLAS_VAULT_SECRET_ID }}
#         secrets: |
#             /system/aws/atlas-dev/terraform-user aws_access_key_id | AWS_ACCESS_KEY_ID ;
#             /system/aws/atlas-dev/terraform-user aws_secret_access_key | AWS_SECRET_ACCESS_KEY

#     - name: Deploy to S3 DEV
#       uses: jakejarvis/s3-sync-action@master
#       with:
#         args: --acl public-read --delete
#       env:
#         AWS_S3_BUCKET: "%Subdomain%.theatlastango.com" # TODO: Replace '%Subdomain%' with dev deployment subdomain, e.g. 'apollo-jupiter-atlas-dev.admin-dev'
#         AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: "us-west-2"
#         SOURCE_DIR: "build"
